import img1 from "../../../public/profile_pic.jpg";
import img2 from "../../../public/profile_pic.jpg";
import img3 from "../../../public/profile_pic.jpg";

export const table = [
    // Customer 1
    {
        id: 1,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Gutter',
        quantity: 36,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 5000,
        cost: 5000,
        payment_method: "POS",
        supplied_by: "Paul",
    },
    {
        id: 2,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Pipe',
        quantity: 24,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 4000,
        cost: 4000,
        payment_method: "Bank",
        supplied_by: "Paul",
    },
    {
        id: 3,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Stop End',
        quantity: 12,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 2500,
        cost: 2500,
        payment_method: "Transfer",
        supplied_by: "Paul",
    },
    {
        id: 4,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Socket',
        quantity: 15,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 6500,
        cost: 6500,
        payment_method: "POS",
        supplied_by: "Paul",
    },
    {
        id: 5,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Clip',
        quantity: 20,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 17500,
        cost: 17500,
        payment_method: "Transfer",
        supplied_by: "Paul",
    },
    {
        id: 6,
        orderId: 8765543,
        customer: img1,
        customer_name: 'John Doe',
        item: 'Joiner',
        quantity: 25,
        location: '1T4 Road, Ekpoma, Edo State',
        date: '13 Dec, 2024',
        time: '02:00 AM',
        status: 'pending',
        paid: 9000,
        cost: 9000,
        payment_method: "Bank",
        supplied_by: "Paul",
    },
    
    // Customer 2
    {
        id: 7,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Funnel',
        quantity: 30,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 50000,
        cost: 50000,
        payment_method: "POS",
        supplied_by: "Emma",
    },
    {
        id: 8,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Elbow',
        quantity: 15,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 10500,
        cost: 10500,
        payment_method: "POS",
        supplied_by: "Emma",
    },
    {
        id: 9,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Connector',
        quantity: 20,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 8000,
        cost: 8000,
        payment_method: "Bank",
        supplied_by: "Emma",
    },
    {
        id: 10,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Valve',
        quantity: 18,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 6000,
        cost: 6000,
        payment_method: "Bank",
        supplied_by: "Emma",
    },
    {
        id: 11,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Seal',
        quantity: 25,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 7500,
        cost: 7500,
        payment_method: "Transfer",
        supplied_by: "Emma",
    },
    {
        id: 12,
        orderId: 8765544,
        customer: img2,
        customer_name: 'Jane Smith',
        item: 'Adapter',
        quantity: 30,
        location: '2B Street, Lagos',
        date: '14 Dec, 2024',
        time: '03:00 PM',
        status: 'pending',
        paid: 9000,
        cost: 9000,
        payment_method: "POS",
        supplied_by: "Emma",
    },

    // Customer 3
    {
        id: 13,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Stop End',
        quantity: 10,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 2500,
        cost: 2500,
        payment_method: "Transfer",
        supplied_by: "Paul",
    },
    {
        id: 14,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Socket',
        quantity: 14,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 6500,
        cost: 6500,
        payment_method: "POS",
        supplied_by: "Paul",
    },
    {
        id: 15,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Clip',
        quantity: 20,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 17500,
        cost: 17500,
        payment_method: "Transfer",
        supplied_by: "Paul",
    },
    {
        id: 16,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Joiner',
        quantity: 25,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 9000,
        cost: 9000,
        payment_method: "Bank",
        supplied_by: "Paul",
    },
    {
        id: 17,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Funnel',
        quantity: 30,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 50000,
        cost: 50000,
        payment_method: "POS",
        supplied_by: "Paul",
    },
    {
        id: 18,
        orderId: 8765545,
        customer: img3,
        customer_name: 'Alice Johnson',
        item: 'Elbow',
        quantity: 15,
        location: '3C Avenue, Abuja',
        date: '15 Dec, 2024',
        time: '11:00 AM',
        status: 'pending',
        paid: 10500,
        cost: 10500,
        payment_method: "POS",
        supplied_by: "Paul",
    },
];
